### ISSUE TITLE
Decoerate metoda

### ISSUE THREAD

**Issue by thekarinka** [chriskorinek/mapy-api-ts-types#6]
V definici není správně zohledněna decorate metoda z http://api.mapy.cz/doc/SMap.Marker.Feature.Card.html

**Comment by bobkorinek** [comment]
Na konci tohoto dne vydám novou verzi s opravou :+1:

**Comment by bobkorinek** [comment]
Pokusil jsem se problém opravit ve [verzi 1.1.3](https://github.com/chriskorinek/mapy-api-ts-types/tree/1.1.3), ale byl to relativně problém kvůli dědičnosti. Díky tomu, že třída `SMap.Marker.Feature.Card` dědí  `JAK.AbstractDecorator` a `JAK.AbstractDecorator` má definovanou metoda `decorate` pouze s jedním argumentem, ale třída `SMap.Marker.Feature.Card` má se dvěma argumentama, tak TypeScript hlásil chybu kvůli špatné definici této metody. Z toho důvodu jsem musel pro třídu `SMap.Marker.Feature.Card` definovat dvě tyto metody, kde jedna má jenom jeden argument a druhá obadva. Doufám, že s tím nebude žádný problém, případně kdyby byl nápad, jak tohle vyřešit jinak, tak bude jen rád 😉
